version: '3'
services:
    nginx:
        ports:
            - '80:80'
    node-app:
        build: .
        image: sazzadzihan/node-blogpost-app
        depends_on:
            - mongo
        volumes:
            - ./:/app
            - /app/node_modules
        environment:
            - NODE_ENV=production
            - SESSION_SECRET=${SESSION_SECRET}
            - REDIS_URL=redis
            - MONGODB_HOST=mongo
        command: yarn start

    mongo:
        image: mongo
        ports:
            - '27017:27017'
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
            - MONGO_PORT=27017

        volumes:
            - mongo-db-production:/data/db

    redis:
        image: redis

volumes:
    mongo-db-production:
